### ISSUE TITLE
Show how many hours/days ago news was published.

### ISSUE THREAD

**Issue by AnuragThePathak** [AnuragThePathak/News-Feed-App#9]
Show hours if it's less than 24 otherwise show days.

**Comment by gururani-abhishek** [comment]
@AnuragThePathak I want to work on this, I've dealt with the same news API while building a similar news feed application, I'll fetch it in the repository, will store it in the database, make some changes in the row_item.xml and then display time according to the conditions you have provided.

**Comment by gururani-abhishek** [comment]
so I was working on it, but I'm not able to fetch 'publishedAt' from the  API you are using. I'm simply getString("publishedAt") from the jsonObject that has used in the code base, what can I do? 
API : https://saurav.tech/NewsAPI/top-headlines/category/general/in.json

**Comment by AnuragThePathak** [comment]
How did you know you are not able to fetch publishedAt?

**Comment by gururani-abhishek** [comment]
Because when I fetch it and run the app, the app fails to start.

**Comment by gururani-abhishek** [comment]
This issue can be closed now. Also a suggestion, next time if you review someone's PR, please be more concise and clear. It wasted a lot of my time, wondering how to create a separate script, me coming from a Linux bkg, script is a whole different thing...lol.

**Comment by AnuragThePathak** [comment]
> This issue can be closed now. Also a suggestion, next time if you review someone's PR, please be more concise and clear. It wasted a lot of my time, wondering how to create a separate script, me coming from a Linux bkg, script is a whole different thing...lol. @AnuragThePathak

Yes I am maintaining repo for the first time so...
Also I thought that you are aware of kotlin scripts.
Btw your changes didn't work because you have modified data entity but not upgraded DB.

**Comment by gururani-abhishek** [comment]
It is working on my system

**Comment by gururani-abhishek** [comment]
As you can see, I added a new column  time in News class, made changes in the repository. Saved fetched publishedAt to the newly  added column time. Why  would there be any requirement to modify the DB as it has already been built in such fashion that if we add a new column to News class things should work fine, no?

**Comment by AnuragThePathak** [comment]
> It is working on my system

Well it was being crashed when I tested so updated version.

**Comment by AnuragThePathak** [comment]
> ahh, so we have to update the version with every new column or entity we add in the database?

Yes that's what I understand. But I haven't learnt migration.
